package GUI;

import classes.Admin;
import classes.Staff;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class AdminLog extends javax.swing.JFrame {
  Staff admin = main.staff;
  public AdminLog() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jScrollPane2 = new javax.swing.JScrollPane();
    logs_table = new javax.swing.JTable();
    jLabel2 = new javax.swing.JLabel();
    user_name_field = new javax.swing.JTextField();
    search_button = new javax.swing.JButton();
    jLabel1 = new javax.swing.JLabel();
    back_button = new javax.swing.JButton();
    manager_button = new javax.swing.JButton();
    officer_button = new javax.swing.JButton();
    admin_button = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    logs_table.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
    logs_table.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {

      },
      new String [] {
        "User name", "Log type", "Date", "Time"
      }
    ) {
      Class[] types = new Class [] {
        java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
      };
      boolean[] canEdit = new boolean [] {
        false, false, false, false
      };

      public Class getColumnClass(int columnIndex) {
        return types [columnIndex];
      }

      public boolean isCellEditable(int rowIndex, int columnIndex) {
        return canEdit [columnIndex];
      }
    });
    logs_table.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        logs_tableMouseClicked(evt);
      }
    });
    jScrollPane2.setViewportView(logs_table);

    jLabel2.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
    jLabel2.setText("User name:");

    user_name_field.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N

    search_button.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
    search_button.setText("Search user name");
    search_button.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        search_buttonActionPerformed(evt);
      }
    });

    jLabel1.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel1.setText("View recorded logs");

    back_button.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
    back_button.setText("Back");
    back_button.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        back_buttonActionPerformed(evt);
      }
    });

    manager_button.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
    manager_button.setText("Show manager logs");
    manager_button.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        manager_buttonActionPerformed(evt);
      }
    });

    officer_button.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
    officer_button.setText("Show officer logs");
    officer_button.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        officer_buttonActionPerformed(evt);
      }
    });

    admin_button.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
    admin_button.setText("Show admin logs");
    admin_button.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        admin_buttonActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(26, 26, 26)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(manager_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(officer_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(back_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(admin_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 625, Short.MAX_VALUE)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(user_name_field, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(search_button)))
            .addGap(0, 0, Short.MAX_VALUE)))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(18, 18, 18)
        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(user_name_field, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(search_button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(17, 17, 17)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(admin_button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(12, 12, 12)
            .addComponent(manager_button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(officer_button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(back_button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE))
          .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE))
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void logs_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logs_tableMouseClicked
    // TODO add your handling code here:

  }//GEN-LAST:event_logs_tableMouseClicked

  private void search_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_buttonActionPerformed
    // TODO add your handling code here:
    String user_name = user_name_field.getText();
    if (user_name_field.equals("")) {
      JOptionPane.showMessageDialog(null, "Enter user name to search");
      showLogsTable(null);
      return;
    }
    List<String> logs_list = ((Admin) admin).getRecordLogs(user_name);
    if (logs_list.isEmpty()) {
      JOptionPane.showMessageDialog(null, "Cannot find recorded log");
      showLogsTable(null);
    } else {
      showLogsTable(logs_list);
    }
  }//GEN-LAST:event_search_buttonActionPerformed

  private void showLogsTable(List<String> logs_list) {    
    DefaultTableModel model = (DefaultTableModel) logs_table.getModel();
    String[] col_name = {"User name", "Log type", "Date", "Time"};
    if (logs_list == null || logs_list.isEmpty()) {
      model.setRowCount(0);
    } else {
      String[][] data = new String[logs_list.size()][4];
      int row_count = 0;
      for (String log: logs_list) {
        data[row_count] = log.split("!");
        row_count++;
      }
      model.setDataVector(data, col_name);
    }
  }
  
  private void back_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_buttonActionPerformed
    // TODO add your handling code here:
    AdminGUI new_GUI = new AdminGUI();
    new_GUI.setVisible(true);
    this.dispose();
  }//GEN-LAST:event_back_buttonActionPerformed

  private void manager_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manager_buttonActionPerformed
    // TODO add your handling code here:
    List<String> manager_logs = ((Admin) admin).getRecordLogs("Manager");
    if (manager_logs.isEmpty()) {
      JOptionPane.showMessageDialog(null, "No manager recorded logs");
    }
    showLogsTable(manager_logs);
  }//GEN-LAST:event_manager_buttonActionPerformed

  private void officer_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_officer_buttonActionPerformed
    // TODO add your handling code here:
    List<String> officer_logs = ((Admin) admin).getRecordLogs("Officer");
    if (officer_logs.isEmpty()) {
      JOptionPane.showMessageDialog(null, "No officer recorded logs");
    }
    showLogsTable(officer_logs);
  }//GEN-LAST:event_officer_buttonActionPerformed

  private void admin_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_buttonActionPerformed
    // TODO add your handling code here:
    List<String> admin_logs = ((Admin) admin).getRecordLogs("Admin");
    showLogsTable(admin_logs);
  }//GEN-LAST:event_admin_buttonActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton admin_button;
  private javax.swing.JButton back_button;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JTable logs_table;
  private javax.swing.JButton manager_button;
  private javax.swing.JButton officer_button;
  private javax.swing.JButton search_button;
  private javax.swing.JTextField user_name_field;
  // End of variables declaration//GEN-END:variables
}
