package GUI;

import classes.AccessFile;
import classes.Admin;
import classes.Staff;
import java.util.List;
import javax.swing.JOptionPane;

public class AdminEdit extends javax.swing.JFrame {
  Staff admin = main.staff;
  /**
   * Creates new form Admin_Edit_Staff
   */
  public AdminEdit() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    name_field = new javax.swing.JTextField();
    address_field = new javax.swing.JTextField();
    phone_field = new javax.swing.JTextField();
    user_name_field = new javax.swing.JTextField();
    password_field = new javax.swing.JTextField();
    role_box = new javax.swing.JComboBox<>();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();
    jLabel7 = new javax.swing.JLabel();
    back_button = new javax.swing.JButton();
    save_button = new javax.swing.JButton();
    id_field = new javax.swing.JTextField();
    jLabel8 = new javax.swing.JLabel();
    search_button = new javax.swing.JButton();
    jLabel9 = new javax.swing.JLabel();
    id_label = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    name_field.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N

    address_field.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N

    phone_field.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N

    user_name_field.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N

    password_field.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N

    role_box.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
    role_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manager", "Officer", "Admin" }));

    jLabel1.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel1.setText("Edit staff");

    jLabel2.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
    jLabel2.setText("Address:");

    jLabel3.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
    jLabel3.setText("Role:");

    jLabel4.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
    jLabel4.setText("Phone:");

    jLabel5.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
    jLabel5.setText("User name:");

    jLabel6.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
    jLabel6.setText("Password:");

    jLabel7.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
    jLabel7.setText("Fullname:");

    back_button.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
    back_button.setText("Back");
    back_button.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        back_buttonActionPerformed(evt);
      }
    });

    save_button.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
    save_button.setText("Save");
    save_button.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        save_buttonActionPerformed(evt);
      }
    });

    id_field.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N

    jLabel8.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
    jLabel8.setText("Search ID");

    search_button.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
    search_button.setText("Search");
    search_button.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        search_buttonActionPerformed(evt);
      }
    });

    jLabel9.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
    jLabel9.setText("Staff ID :");

    id_label.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
    id_label.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
              .addGap(24, 24, 24)
              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addGroup(layout.createSequentialGroup()
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addGap(18, 18, 18)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(address_field)
                    .addComponent(phone_field)))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addGap(18, 18, 18)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(user_name_field)
                    .addComponent(password_field, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)))))
            .addGroup(layout.createSequentialGroup()
              .addGap(109, 109, 109)
              .addComponent(save_button, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addGap(46, 46, 46)
              .addComponent(back_button, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
          .addGroup(layout.createSequentialGroup()
            .addGap(24, 24, 24)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createSequentialGroup()
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                  .addComponent(search_button, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(id_field)
                  .addComponent(name_field)
                  .addComponent(role_box, 0, 268, Short.MAX_VALUE)
                  .addComponent(id_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
              .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)))))
        .addContainerGap(24, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(23, 23, 23)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(id_field, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(search_button)
            .addGap(18, 18, 18)
            .addComponent(id_label, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(layout.createSequentialGroup()
            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(92, 92, 92)
            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(name_field, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(role_box, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(layout.createSequentialGroup()
            .addComponent(user_name_field, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(password_field, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(layout.createSequentialGroup()
            .addComponent(address_field, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(phone_field, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(back_button)
          .addComponent(save_button))
        .addContainerGap(22, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void back_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_buttonActionPerformed
    // TODO add your handling code here:
    AdminGUI admin_view = new AdminGUI();
    this.dispose();
    admin_view.setLocationRelativeTo(null);
    admin_view.setVisible(true);
  }//GEN-LAST:event_back_buttonActionPerformed

  private void save_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_buttonActionPerformed
    // TODO add your handling code here:
    String staff_id, new_name, new_role, new_address, new_phone, new_acc, new_pass, found = "";
    staff_id = id_label.getText();
    if (staff_id.equals("")) {
        JOptionPane.showMessageDialog(null, "No staff information to edit. Search staff first");
        return;
    } else {
      try {
        if (Integer.parseInt(staff_id) <= 0) {
          JOptionPane.showMessageDialog(null, "Invalid ID");
          id_label.setText("");
          name_field.setText("");
          user_name_field.setText("");
          password_field.setText("");
          address_field.setText("");
          phone_field.setText("");
          return;
        }
      } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Invalid ID");
        id_label.setText("");
        name_field.setText("");
        user_name_field.setText("");
        password_field.setText("");
        address_field.setText("");
        phone_field.setText("");
        return;
      }
    }
    List<String> found_staff = ((Admin) admin).findStaff(staff_id);
    if (found_staff.isEmpty()) {
      JOptionPane.showMessageDialog(null, "Cannot find staff id: "+staff_id);
      id_label.setText("");
      name_field.setText("");
      user_name_field.setText("");
      password_field.setText("");
      address_field.setText("");
      phone_field.setText("");
      return;
    }
    Staff edit_staff = new Staff(Integer.parseInt(staff_id));
    new_name = name_field.getText();
    if (new_name.equals("")) {
      JOptionPane.showMessageDialog(null, "No name. Enter staff name");
      return;
    } else if (((Admin) admin).checkDuplicatedStaff(edit_staff.getID()+"", new_name)) {
      JOptionPane.showMessageDialog(null, "Duplicated staff name");
      return;
    }
    new_role = role_box.getSelectedItem().toString();
    if (!edit_staff.getRole().equals("Admin") & new_role.equals("Admin")) {
      JOptionPane.showMessageDialog(null, "Cannot assign role as Admin. There is only one Admin");
      return;
    }
    new_acc = user_name_field.getText();
    if (new_acc.equals("")) {
      JOptionPane.showMessageDialog(null, "No user name. Enter staff user name");
      return;
    } else if(((Admin) admin).checkDuplicatedUserName(edit_staff.getID()+"", new_acc)) {
        JOptionPane.showMessageDialog(null, "Duplicated user name. Enter different user name");
        return;
    }
    new_pass = password_field.getText();
    if (new_pass.equals("")) {
      JOptionPane.showMessageDialog(null, "No password. Enter staff password");
      return;
    }
    new_address = address_field.getText();
    if (new_address.equals("")) {
      JOptionPane.showMessageDialog(null, "No address. Enter staff address");
      return;
    } 
    new_phone = phone_field.getText();
    if (new_phone.equals("")) {
      JOptionPane.showMessageDialog(null, "No phone. Enter staff phone");
      return;
    } else if (new_phone.length() < 9) {
      JOptionPane.showMessageDialog(null, "Invalid phone number. Phone number must have at least 9 digits");
      return;
    } else if (new_phone.charAt(0) != '0') {
      JOptionPane.showMessageDialog(null, "Invalid phone number. Phone number must start with 0");
      return;
    } else {
      try {
        Integer.parseInt(new_phone);
      } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Not number. Enter phone number as number");
        return;
      }
    }
    if (edit_staff.getName().equals(new_name) & edit_staff.getRole().equals(new_role) & 
        edit_staff.getUserName().equals(new_acc) & edit_staff.getPassword().equals(new_pass) & 
        edit_staff.getAddress().equals(new_address) & edit_staff.getPhone().equals(new_phone)) {
      JOptionPane.showMessageDialog(null, "There is no change");
    } else {
      int dialog_button = JOptionPane.YES_NO_OPTION;
      int dialog_result = JOptionPane.showConfirmDialog(null, "Do you want to edit this staff?","Edit confirmation",dialog_button);
      if (dialog_result == 0) {
        edit_staff.setName(new_name);
        edit_staff.setRole(new_role);
        edit_staff.setUserName(new_acc);
        edit_staff.setPassword(new_pass);
        edit_staff.setAddress(new_address);
        edit_staff.setPhone(new_phone);
        ((Admin) admin).editStaff(edit_staff);
        JOptionPane.showMessageDialog(null, "Staff ID: " + staff_id + " is editted");
      } else {
        JOptionPane.showMessageDialog(null, "Staff ID: " + staff_id + " is not editted");
      }
    }
  }//GEN-LAST:event_save_buttonActionPerformed

  private void search_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_buttonActionPerformed
    // TODO add your handling code here:
    String id = id_field.getText();
    if (id.equals("")) {
      JOptionPane.showMessageDialog(null, "Enter staff ID to search");
      return;
    }  else {
      try {
        Integer.parseInt(id);
      } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "ID is not number. Enter ID as number");
        return;
      }
      if (Integer.parseInt(id) <= 0) {
        JOptionPane.showMessageDialog(null, "Invalid ID");
        return;
      }
    }

    id = id_field.getText();
    List<String> staff_list = AccessFile.getFile("data/staff.txt");
    String found_staff = null;
    for (String staff: staff_list) {
      if (staff.split("!")[0].equals(id)) {
        found_staff = staff;
        break;
      }
    }
    if (found_staff == null) {
      JOptionPane.showMessageDialog(null, "Cannot find staff with ID: " + id);
      id_label.setText("");
      name_field.setText("");
      user_name_field.setText("");
      password_field.setText("");
      address_field.setText("");
      phone_field.setText("");
    } else {
      String[] pieces = found_staff.split("!");
      id_label.setText(pieces[0]);
      name_field.setText(pieces[1]);
      role_box.setSelectedItem(pieces[2]);
      user_name_field.setText(pieces[3]);
      password_field.setText(pieces[4]);
      address_field.setText(pieces[5]);
      phone_field.setText(pieces[6]);
    }
  }//GEN-LAST:event_search_buttonActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTextField address_field;
  private javax.swing.JButton back_button;
  private javax.swing.JTextField id_field;
  private javax.swing.JLabel id_label;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JLabel jLabel9;
  private javax.swing.JTextField name_field;
  private javax.swing.JTextField password_field;
  private javax.swing.JTextField phone_field;
  private javax.swing.JComboBox<String> role_box;
  private javax.swing.JButton save_button;
  private javax.swing.JButton search_button;
  private javax.swing.JTextField user_name_field;
  // End of variables declaration//GEN-END:variables
}
