package GUI;

import classes.Manager;
import classes.Staff;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class ManagerTenderApply extends javax.swing.JFrame {
  Staff manager = main.staff;
  /**
   * Creates new form ManagerTenderSetFormula
   */
  public ManagerTenderApply() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    tender_id_field = new javax.swing.JTextField();
    search_button = new javax.swing.JButton();
    apply_discount_button = new javax.swing.JButton();
    jLabel1 = new javax.swing.JLabel();
    help_button = new javax.swing.JButton();
    back_button = new javax.swing.JButton();
    jScrollPane1 = new javax.swing.JScrollPane();
    tender_products_table = new javax.swing.JTable();
    jLabel2 = new javax.swing.JLabel();
    discount_field = new javax.swing.JTextField();
    jLabel3 = new javax.swing.JLabel();
    tender_id_label = new javax.swing.JLabel();
    name_label = new javax.swing.JLabel();
    price_label = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    tender_id_field.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N

    search_button.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
    search_button.setText("Search");
    search_button.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        search_buttonActionPerformed(evt);
      }
    });

    apply_discount_button.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
    apply_discount_button.setText("Apply discount");
    apply_discount_button.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        apply_discount_buttonActionPerformed(evt);
      }
    });

    jLabel1.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel1.setText("Apply discount to products in a tendering request");

    help_button.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
    help_button.setText("Help");
    help_button.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        help_buttonActionPerformed(evt);
      }
    });

    back_button.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
    back_button.setText("Back");
    back_button.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        back_buttonActionPerformed(evt);
      }
    });

    tender_products_table.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
    tender_products_table.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {

      },
      new String [] {
        "ID", "Brand", "Model", "Type", "Original Price", "Discount (%)", "Discount Price", "Quantity"
      }
    ) {
      boolean[] canEdit = new boolean [] {
        false, false, false, false, false, false, false, false
      };

      public boolean isCellEditable(int rowIndex, int columnIndex) {
        return canEdit [columnIndex];
      }
    });
    jScrollPane1.setViewportView(tender_products_table);

    jLabel2.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
    jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    jLabel2.setText("Tender ID:");

    discount_field.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N

    jLabel3.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
    jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    jLabel3.setText("Discount (%):");

    tender_id_label.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
    tender_id_label.setText("Tender ID:  ");

    name_label.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
    name_label.setText("Name: ");

    price_label.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
    price_label.setText("Total products price: ");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(19, 19, 19)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(help_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(back_button, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE))
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE))
          .addGroup(layout.createSequentialGroup()
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createSequentialGroup()
                .addComponent(tender_id_label, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(name_label, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(price_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
              .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(tender_id_field, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(discount_field, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(apply_discount_button)
                  .addComponent(search_button, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(332, 332, 332))
              .addComponent(jScrollPane1))
            .addContainerGap())))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(21, 21, 21)
        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(tender_id_field, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(search_button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(apply_discount_button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(discount_field, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(name_label, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(tender_id_label, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(price_label, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(help_button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(back_button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 325, Short.MAX_VALUE))
          .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE))
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void search_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_buttonActionPerformed
    // TODO add your handling code here:
    String tender_id = tender_id_field.getText();
    if (tender_id.equals("")) {
      JOptionPane.showMessageDialog(null, "Enter tender ID to search");
      tender_id_label.setText("Tender ID: ");
      name_label.setText("Name: ");
      price_label.setText("Total products price: ");
      discount_field.setText("");
      return;
    } else {
      try {
        if (Integer.parseInt(tender_id) <= 0) {
          JOptionPane.showMessageDialog(null, "Invalid ID");
          tender_id_label.setText("Tender ID: ");
          name_label.setText("Name: ");
          price_label.setText("Total products price: ");
          discount_field.setText("");
          return;
        }
      } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Invalid ID");
        tender_id_label.setText("Tender ID: ");
        name_label.setText("Name: ");
        price_label.setText("Total products price: ");
        discount_field.setText("");
        return;
      }      
    }
    List<String> found_tender = ((Manager) manager).searchTender(tender_id);
    if (found_tender.isEmpty()) {
      JOptionPane.showMessageDialog(null, "Cannot find tender ID: "+tender_id);
      showProductsTable(new ArrayList<>());
      tender_id_label.setText("Tender ID: ");
      name_label.setText("Name: ");
      price_label.setText("Total products price: ");
      return;
    } 
    List<String> tender_products = ((Manager) manager).getTenderProducts(tender_id);
    if (tender_products.isEmpty()) {
      JOptionPane.showMessageDialog(null, "There is no product in tender ID: " + tender_id + ". Tendering officer should add products first");
      tender_id_label.setText("Tender ID: ");
      name_label.setText("Name: ");
      price_label.setText("Total products price: ");
    } else {
      String[] pieces = found_tender.get(0).split("!");
      tender_id_label.setText("Tender ID: " + pieces[0]);
      name_label.setText("Name: " + pieces[1]);
      price_label.setText("Total products price: RM" + pieces[3]);
    }
    showProductsTable(tender_products);
  }//GEN-LAST:event_search_buttonActionPerformed

  private void showProductsTable(List<String> tender_products) {
    DefaultTableModel model = (DefaultTableModel) tender_products_table.getModel();
    String[] cols = {"ID", "Brand", "Model", "Type", "Original Price", "Discount (%)", "Discount Price", "Quantity"};          
    String[][] rows = new String[tender_products.size()][8];
    if (tender_products.isEmpty()) {
      rows = new String[0][8];
    } else {
      int row_count = 0;
      for (String product: tender_products) {
        rows[row_count] = product.split("!");
        row_count++;
      }
    }
    model.setDataVector(rows, cols);
  }

  private void apply_discount_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apply_discount_buttonActionPerformed
    // TODO add your handling code here:
    if (tender_products_table.getSelectedRow() == -1) {
      if (tender_products_table.getRowCount() == 0) {
        JOptionPane.showMessageDialog(null, "There is no product in the table.");
      } else {
        JOptionPane.showMessageDialog(null, "Select a product in the table to apply discount");
      }
      return;
    }
    String tender_id, products_price;
    String discount = discount_field.getText();
    if (discount.equals("")) {
      JOptionPane.showMessageDialog(null, "No discount %. Enter discount %");
      return;
    } else  {
      try {
        if (Float.parseFloat(discount) < 0 || Float.parseFloat(discount) > 100) {
          JOptionPane.showMessageDialog(null, "Invalid discount %");
          return;
        }
      } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Invalid discount");
        return;
      }
    }    
    int row = tender_products_table.getSelectedRow();
    String product_id = tender_products_table.getValueAt(row, 0)+"";
    int dialog_button = JOptionPane.YES_NO_OPTION;
    int dialog_result = JOptionPane.showConfirmDialog(null, "Do you want to apply " + discount + "% discount to product ID: " + product_id, "Apply discount confirmation",dialog_button);
    if (dialog_result == 0) {
      tender_id = tender_id_label.getText().split(": ")[1];
      float discount_price = Float.parseFloat(tender_products_table.getValueAt(row, 4)+"") * (1-Float.parseFloat(discount)/100);
      tender_products_table.setValueAt(discount, row, 5);
      tender_products_table.setValueAt(discount_price, row, 6);
      products_price = ""+((Manager) manager).applyDiscount(tender_id, product_id, discount, discount_price+"");
      price_label.setText("Total products price: RM"+products_price);
      discount_field.setText("");
      JOptionPane.showMessageDialog(null, discount + "% discount is applied to product ID: " + product_id);
    } else {
      JOptionPane.showMessageDialog(null, discount + "% discount is not applied to product ID: " + product_id);
    }
  }//GEN-LAST:event_apply_discount_buttonActionPerformed

  private void help_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_help_buttonActionPerformed
    // TODO add your handling code here:
    String help = "";
    help += "  - Search: Enter a tender ID to display all products in the tendering request\n\n";
    help += "  - Apply discount: \n";
    help += "        1. Click one product the product in the table to apply discount.\n";
    help += "        2. Enter discount percentage \n";
    help += "        3. Click \"Apply discount\" button\n\n";
    help += "  - Back: Go back to previous menu\n";
    JOptionPane.showMessageDialog(null, help, "Apply discount help", WIDTH);
  }//GEN-LAST:event_help_buttonActionPerformed

  private void back_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_buttonActionPerformed
    // TODO add your handling code here:
    ManagerGUI new_GUI = new ManagerGUI();
    new_GUI.setLocationRelativeTo(null);
    new_GUI.setVisible(true);
    this.dispose();
  }//GEN-LAST:event_back_buttonActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton apply_discount_button;
  private javax.swing.JButton back_button;
  private javax.swing.JTextField discount_field;
  private javax.swing.JButton help_button;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JLabel name_label;
  private javax.swing.JLabel price_label;
  private javax.swing.JButton search_button;
  private javax.swing.JTextField tender_id_field;
  private javax.swing.JLabel tender_id_label;
  private javax.swing.JTable tender_products_table;
  // End of variables declaration//GEN-END:variables
}
