package GUI;

import classes.Manager;
import classes.Tender;
import classes.Staff;
import java.util.List;
import javax.swing.JOptionPane;

public class ManagerTenderEdit extends javax.swing.JFrame {
  Staff manager = main.staff;
  /**
   * Creates new form ManagerTenderEdit
   */
  public ManagerTenderEdit() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    name_field = new javax.swing.JTextField();
    deadline_field = new javax.swing.JTextField();
    jLabel7 = new javax.swing.JLabel();
    created_date_field = new javax.swing.JTextField();
    back_button = new javax.swing.JButton();
    save_button = new javax.swing.JButton();
    id_field = new javax.swing.JTextField();
    status_box = new javax.swing.JComboBox<>();
    jLabel8 = new javax.swing.JLabel();
    jLabel1 = new javax.swing.JLabel();
    search_button = new javax.swing.JButton();
    jLabel2 = new javax.swing.JLabel();
    id_label = new javax.swing.JLabel();
    jLabel9 = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    jLabel3.setText("Status :");

    jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    jLabel4.setText("Created Date :");

    name_field.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

    deadline_field.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

    jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    jLabel7.setText("Name :");

    created_date_field.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

    back_button.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    back_button.setText("Back");
    back_button.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        back_buttonActionPerformed(evt);
      }
    });

    save_button.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    save_button.setText("Save");
    save_button.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        save_buttonActionPerformed(evt);
      }
    });

    id_field.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

    status_box.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
    status_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pending", "In Progress", "Submitted" }));

    jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    jLabel8.setText("Search ID :");

    jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel1.setText("Edit tendering request");

    search_button.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    search_button.setText("Search");
    search_button.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        search_buttonActionPerformed(evt);
      }
    });

    jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    jLabel2.setText("Deadline :");

    id_label.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
    id_label.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

    jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    jLabel9.setText("Tender ID :");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGap(123, 123, 123)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(layout.createSequentialGroup()
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(status_box, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addGroup(layout.createSequentialGroup()
                  .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(18, 18, 18)
                  .addComponent(deadline_field))
                .addGroup(layout.createSequentialGroup()
                  .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(18, 18, 18)
                  .addComponent(created_date_field, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createSequentialGroup()
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addGap(18, 18, 18)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                      .addComponent(id_field, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                      .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(search_button, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)))
                    .addComponent(id_label, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createSequentialGroup()
                  .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(18, 18, 18)
                  .addComponent(name_field))))))
        .addContainerGap(20, Short.MAX_VALUE))
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addGap(0, 0, Short.MAX_VALUE)
        .addComponent(save_button, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(44, 44, 44)
        .addComponent(back_button, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(97, 97, 97))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(18, 18, 18)
        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(id_field, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(14, 14, 14)
        .addComponent(search_button)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(id_label, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(name_field, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(deadline_field, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(status_box, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(created_date_field, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(back_button)
          .addComponent(save_button))
        .addGap(18, 18, 18))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void back_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_buttonActionPerformed
    // TODO add your handling code here:
    ManagerGUI manager_GUI = new ManagerGUI();
    manager_GUI.setLocationRelativeTo(null);
    manager_GUI.setVisible(true);          
    this.dispose();
  }//GEN-LAST:event_back_buttonActionPerformed

  private void save_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_buttonActionPerformed
    // TODO add your handling code here:
    String tender_id, new_name, new_deadline, new_status, new_date, found_tender = null;
    tender_id = id_label.getText();
    new_name = name_field.getText();
    new_deadline = deadline_field.getText();
    new_status = status_box.getSelectedItem().toString();
    new_date = created_date_field.getText();
    if (tender_id.equals("")) {
      JOptionPane.showMessageDialog(null, "No tender information. Search tendering request first");
      id_label.setText("");
      name_field.setText("");
      deadline_field.setText("");
      created_date_field.setText("");
      return;
    } else {
      try {
        if (Integer.parseInt(tender_id) <= 0) {
          JOptionPane.showMessageDialog(null, "Invalid ID");
          id_label.setText("");
          name_field.setText("");
          deadline_field.setText("");
          created_date_field.setText("");
          return;
        }
      } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Invalid ID");
        id_label.setText("");
        name_field.setText("");
        deadline_field.setText("");
        created_date_field.setText("");
        return;
      }
    }
    Tender edit_tender = new Tender(Integer.parseInt(tender_id));
    if (edit_tender.checkDuplicateTender(new_name)) {
      JOptionPane.showMessageDialog(null, "Duplicated tender name");
      return;
    }
    if (edit_tender.getName().equals(new_name) & edit_tender.getDeadline().equals(new_deadline) &
        edit_tender.getStatus().equals(new_status) & edit_tender.getDate().equals(new_date)) {
        JOptionPane.showMessageDialog(null, "There is no change");
    } else {
      int dialog_button = JOptionPane.YES_NO_OPTION;
      int dialog_result = JOptionPane.showConfirmDialog(null, "Do you want to edit this tendering request?","Edit confirmation",dialog_button);
      if (dialog_result == 0) {
        if (edit_tender.getName().equals(new_name)) {
          edit_tender.setDeadline(new_deadline);
          edit_tender.setStatus(new_status);
          edit_tender.setDate(new_date);
          ((Manager) manager).editTender(edit_tender, false);
        } else {
          edit_tender.setName(new_name);
          edit_tender.setDeadline(new_deadline);
          edit_tender.setStatus(new_status);
          edit_tender.setDate(new_date);
          ((Manager) manager).editTender(edit_tender, true);
        }
        JOptionPane.showMessageDialog(null, "The tendering request is editted");
        id_field.setText("");
        id_label.setText("");
        name_field.setText("");
        deadline_field.setText("");
        created_date_field.setText("");
      } else {
        JOptionPane.showMessageDialog(null, "The tendering request is not editted");
      }
    }
  }//GEN-LAST:event_save_buttonActionPerformed

  private void search_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_buttonActionPerformed
    // TODO add your handling code here:
    String id = id_field.getText();
    if (id.equals("")) {
      JOptionPane.showMessageDialog(null, "Enter tender ID to search");
      return;
    } else {
      try {
        if (Integer.parseInt(id) <= 0) {
          JOptionPane.showMessageDialog(null, "Invalid ID");
          id_label.setText("");
          name_field.setText("");
          deadline_field.setText("");
          created_date_field.setText("");
          return;
        }
      } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Invalid ID");
        id_label.setText("");
        name_field.setText("");
        deadline_field.setText("");
        created_date_field.setText("");
        return;
      }
    }
    List<String> found_tender = ((Manager) manager).searchTender(id);
    if (found_tender.size() == 0) {
      JOptionPane.showMessageDialog(null, "Cannot find tender ID: " + id);
      id_label.setText("");
      name_field.setText("");
      deadline_field.setText("");
      created_date_field.setText("");
      return;
    }
    String[] pieces = found_tender.get(0).split("!");
    id_label.setText(pieces[0]);
    name_field.setText(pieces[1]);
    deadline_field.setText(pieces[7]);
    status_box.setSelectedItem(pieces[8]);
    created_date_field.setText(pieces[9]);
  }//GEN-LAST:event_search_buttonActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton back_button;
  private javax.swing.JTextField created_date_field;
  private javax.swing.JTextField deadline_field;
  private javax.swing.JTextField id_field;
  private javax.swing.JLabel id_label;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JLabel jLabel9;
  private javax.swing.JTextField name_field;
  private javax.swing.JButton save_button;
  private javax.swing.JButton search_button;
  private javax.swing.JComboBox<String> status_box;
  // End of variables declaration//GEN-END:variables
}
