package GUI;

import classes.Manager;
import classes.Product;
import classes.Staff;
import javax.swing.JOptionPane;

public class ManagerProductsEdit extends javax.swing.JFrame {
  Staff manager = main.staff;
  /**
   * Creates new form ManagerProductsEdit
   */
  public ManagerProductsEdit() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    search_button = new javax.swing.JButton();
    brand_field = new javax.swing.JTextField();
    jLabel2 = new javax.swing.JLabel();
    model_field = new javax.swing.JTextField();
    id_label = new javax.swing.JLabel();
    jLabel7 = new javax.swing.JLabel();
    jLabel9 = new javax.swing.JLabel();
    type_field = new javax.swing.JTextField();
    id_field = new javax.swing.JTextField();
    price_field = new javax.swing.JTextField();
    jLabel5 = new javax.swing.JLabel();
    back_button = new javax.swing.JButton();
    save_button = new javax.swing.JButton();
    jLabel10 = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jLabel1.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel1.setText("Edit product");

    jLabel4.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
    jLabel4.setText("Type :");

    search_button.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
    search_button.setText("Search");
    search_button.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        search_buttonActionPerformed(evt);
      }
    });

    brand_field.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N

    jLabel2.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
    jLabel2.setText("Model :");

    model_field.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N

    id_label.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
    id_label.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

    jLabel7.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
    jLabel7.setText("Brand :");

    jLabel9.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
    jLabel9.setText("Product ID :");

    type_field.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N

    id_field.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N

    price_field.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N

    jLabel5.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
    jLabel5.setText("Price (RM):");

    back_button.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
    back_button.setText("Back");
    back_button.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        back_buttonActionPerformed(evt);
      }
    });

    save_button.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
    save_button.setText("Save");
    save_button.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        save_buttonActionPerformed(evt);
      }
    });

    jLabel10.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
    jLabel10.setText("Search ID :");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addGroup(layout.createSequentialGroup()
            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(price_field, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(layout.createSequentialGroup()
            .addGap(79, 79, 79)
            .addComponent(save_button, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(44, 44, 44)
            .addComponent(back_button, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(id_label, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(layout.createSequentialGroup()
            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(search_button, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(id_field, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
          .addGroup(layout.createSequentialGroup()
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(model_field))
          .addGroup(layout.createSequentialGroup()
            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(type_field, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(layout.createSequentialGroup()
            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(brand_field, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap(21, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(25, 25, 25)
        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(id_field, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(search_button)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(id_label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(brand_field, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(model_field, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(type_field, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(price_field, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(back_button)
          .addComponent(save_button))
        .addContainerGap(18, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void search_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_buttonActionPerformed
    // TODO add your handling code here:
    String id = id_field.getText();
    if (id.equals("")) {
      JOptionPane.showMessageDialog(null, "Enter product ID to search");
      return;
    } else {
      try {
        if (Integer.parseInt(id) <= 0) {
          JOptionPane.showMessageDialog(null, "Invalid ID");
          id_label.setText("");
          brand_field.setText("");
          model_field.setText("");
          type_field.setText("");
          price_field.setText("");
          return;
        }
      } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Invalid ID");
        id_label.setText("");
        brand_field.setText("");
        model_field.setText("");
        type_field.setText("");
        price_field.setText("");
        return;
      }
    }
    Product product = ((Manager) manager).findProduct(id_field.getText());
    if (product == null) {
      JOptionPane.showMessageDialog(null, "Cannot find product");
      id_label.setText("");
      brand_field.setText("");
      model_field.setText("");
      type_field.setText("");
      price_field.setText("");
      return;
    }
    id_label.setText(id_field.getText());
    brand_field.setText(product.getBrand());
    model_field.setText(product.getModel());
    type_field.setText(product.getType());
    price_field.setText(product.getPrice()+"");
  }//GEN-LAST:event_search_buttonActionPerformed

  private void back_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_buttonActionPerformed
    // TODO add your handling code here:
    ManagerProducts new_GUI = new ManagerProducts();
    new_GUI.setLocationRelativeTo(null);
    new_GUI.setVisible(true);
    this.dispose();
  }//GEN-LAST:event_back_buttonActionPerformed

  private void save_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_buttonActionPerformed
    // TODO add your handling code here:
    String product_id, new_brand, new_model, new_type, new_price;
    product_id = id_label.getText();
    if (product_id.equals("")) {
      JOptionPane.showMessageDialog(null, "No product ID to edit");
      return;
    } 
    new_brand = brand_field.getText();
    if (new_brand.equals("")) {
      JOptionPane.showMessageDialog(null, "No brand");
      return;
    }
    new_model = model_field.getText();
    if (new_model.equals("")) {
      JOptionPane.showMessageDialog(null, "No model");
      return;
    }
    new_type = type_field.getText();
    if (new_type.equals("")) {
      JOptionPane.showMessageDialog(null, "No type");
      return;
    }
    new_price = price_field.getText();
    if (new_price.equals("")) {
      JOptionPane.showMessageDialog(null, "No price");
      return;
    }
    try {
      if (Float.parseFloat(new_price) < 0) {
        JOptionPane.showMessageDialog(null, "Invalid price");
        return;
      }
    } catch (NumberFormatException e) {
      JOptionPane.showMessageDialog(null, "Invalid price");
      return;
    }
    Product product = ((Manager) manager).findProduct(id_field.getText());
    if (product.checkDuplicateProduct(new_brand, new_model, new_type)) {
      JOptionPane.showMessageDialog(null, "Duplicated product");
      return;
    }
    if (product.getBrand().equals(new_brand) & product.getModel().equals(new_model) &
        product.getType().equals(new_type) & product.getPrice() == Float.parseFloat(new_price)) {
      JOptionPane.showMessageDialog(null, "There is no change in the current product");
      return;
    }
    int dialog_button = JOptionPane.YES_NO_OPTION;
    int dialog_result = JOptionPane.showConfirmDialog(null, "Do you want to edit the product?","Edit confirmation",dialog_button);
    if (dialog_result == 0) {
      product.setBrand(new_brand);
      product.setType(new_type);
      product.setModel(new_model);
      product.setPrice(Float.parseFloat(new_price));
      ((Manager) manager).editProduct(product);
      JOptionPane.showMessageDialog(null, "Product id: "+product_id+" is editted");
    } else {
      JOptionPane.showMessageDialog(null, "Product id: "+product_id+" is not editted");
    }
  }//GEN-LAST:event_save_buttonActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton back_button;
  private javax.swing.JTextField brand_field;
  private javax.swing.JTextField id_field;
  private javax.swing.JLabel id_label;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel10;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel9;
  private javax.swing.JTextField model_field;
  private javax.swing.JTextField price_field;
  private javax.swing.JButton save_button;
  private javax.swing.JButton search_button;
  private javax.swing.JTextField type_field;
  // End of variables declaration//GEN-END:variables
}
