package GUI;

import classes.Login;
import classes.Tender;
import classes.Staff;
import classes.Manager;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class ManagerGUI extends javax.swing.JFrame {
  Staff manager = main.staff;
  /** Creates new form ManagerGUI */
  public ManagerGUI() {
    initComponents();
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    add_button = new javax.swing.JButton();
    edit_button = new javax.swing.JButton();
    delete_button = new javax.swing.JButton();
    formula_button = new javax.swing.JButton();
    manage_products_button = new javax.swing.JButton();
    jScrollPane1 = new javax.swing.JScrollPane();
    products_table = new javax.swing.JTable();
    jLabel2 = new javax.swing.JLabel();
    id_field = new javax.swing.JTextField();
    search_button = new javax.swing.JButton();
    show_all_button = new javax.swing.JButton();
    apply_discount_button = new javax.swing.JButton();
    logout_button = new javax.swing.JButton();
    report_button = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jLabel1.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel1.setText("MANAGER MAIN MENU");

    add_button.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
    add_button.setText("Add tender");
    add_button.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        add_buttonActionPerformed(evt);
      }
    });

    edit_button.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
    edit_button.setText("Edit tender");
    edit_button.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        edit_buttonActionPerformed(evt);
      }
    });

    delete_button.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
    delete_button.setText("Delete tender");
    delete_button.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        delete_buttonActionPerformed(evt);
      }
    });

    formula_button.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
    formula_button.setText("Set price formula");
    formula_button.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        formula_buttonActionPerformed(evt);
      }
    });

    manage_products_button.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
    manage_products_button.setText("Manage products");
    manage_products_button.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        manage_products_buttonActionPerformed(evt);
      }
    });

    products_table.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
    products_table.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {

      },
      new String [] {
        "ID", "Tender Name", "Tender Price (RM)", "Products Price (RM)", "Tender Discount (RM)", "Labour Cost (RM)", "Mark-up (RM)", "Deadline (dd/mm/yyyy)", "Status", "Create Date (dd/mm/yyyy)", "Create Time"
      }
    ) {
      boolean[] canEdit = new boolean [] {
        false, false, false, false, false, false, false, false, false, false, false
      };

      public boolean isCellEditable(int rowIndex, int columnIndex) {
        return canEdit [columnIndex];
      }
    });
    jScrollPane1.setViewportView(products_table);

    jLabel2.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
    jLabel2.setText("Tender ID:");

    id_field.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N

    search_button.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
    search_button.setText("Search Tender");
    search_button.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        search_buttonActionPerformed(evt);
      }
    });

    show_all_button.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
    show_all_button.setText("Show all");
    show_all_button.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        show_all_buttonActionPerformed(evt);
      }
    });

    apply_discount_button.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
    apply_discount_button.setText("Apply discount");
    apply_discount_button.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        apply_discount_buttonActionPerformed(evt);
      }
    });

    logout_button.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
    logout_button.setText("Logout");
    logout_button.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        logout_buttonActionPerformed(evt);
      }
    });

    report_button.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
    report_button.setText("Generate reports");
    report_button.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        report_buttonActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(21, 21, 21)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(edit_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(add_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(delete_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(manage_products_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(formula_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(show_all_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(apply_discount_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(report_button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE))
          .addGroup(layout.createSequentialGroup()
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(id_field, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(search_button, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(logout_button, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 723, Short.MAX_VALUE))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(19, 19, 19)
        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(id_field, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(search_button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(logout_button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(show_all_button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(add_button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(edit_button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(delete_button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(apply_discount_button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(formula_button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(manage_products_button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(report_button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE))
          .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE))
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void search_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_buttonActionPerformed
    // TODO add your handling code here:
    String id = id_field.getText();
    if (id.equals("")) {
      JOptionPane.showMessageDialog(null, "Enter tender ID to search");
    } else {
      try {
        Integer.parseInt(id);
      } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "ID is not number. Enter ID as number");
        return;
      }
      if (Integer.parseInt(id) < 0) {
        JOptionPane.showMessageDialog(null, "Invalid, negative ID");
        return;
      }
    }
    List<String> found_tender = ((Manager) manager).searchTender(id_field.getText());
    if (found_tender.size() == 0) {
      JOptionPane.showMessageDialog(null, "Cannot find tender ID: "+id_field.getText());
      return;
    }
    showTenderTable(found_tender);
  }//GEN-LAST:event_search_buttonActionPerformed

  private void showTenderTable (List<String> tender_list) {
    DefaultTableModel model = (DefaultTableModel) products_table.getModel();
    String[] col_names = {"ID", "Tender Name", "Tender Price (RM)", "Products Price (RM)", "Tender Discount (RM)", "Labour Cost (RM)", "Mark-up (RM)", "Deadline (dd/mm/yyyy)", "Status", "Create Date (dd/mm/yyyy)", "Created Time"};          
    if (tender_list.isEmpty()) {
      String[][] matrix_data = new String[0][11];
      model.setDataVector(matrix_data, col_names);
    } else {
      String[][] matrix_data = new String[tender_list.size()][11];
      int row_count = 0;
      for (String tender: tender_list) {
        matrix_data[row_count] = tender.split("!");
        row_count++;
      }
      model.setDataVector(matrix_data, col_names);
    }
  }

  private void show_all_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_all_buttonActionPerformed
    // TODO add your handling code here:
    List<String> tender_list = ((Manager) manager).searchTender("all");
    if (tender_list.isEmpty()) {
      JOptionPane.showMessageDialog(null, "There is no tendering request. Manager can add new tendering request");
    }
    showTenderTable(tender_list);
  }//GEN-LAST:event_show_all_buttonActionPerformed

  private void add_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_buttonActionPerformed
    // TODO add your handling code here:
    ManagerTenderAdd new_GUI = new ManagerTenderAdd();
    new_GUI.setLocationRelativeTo(null);
    new_GUI.setVisible(true);
    this.dispose();
  }//GEN-LAST:event_add_buttonActionPerformed

  private void edit_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_buttonActionPerformed
    // TODO add your handling code here:
    ManagerTenderEdit new_GUI = new ManagerTenderEdit();
    new_GUI.setLocationRelativeTo(null);
    new_GUI.setVisible(true);
    this.dispose();
  }//GEN-LAST:event_edit_buttonActionPerformed

  private void delete_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_buttonActionPerformed
    // TODO add your handling code here:
    DefaultTableModel model = (DefaultTableModel) products_table.getModel();
    if (products_table.getSelectedRow() == -1) {
      if (products_table.getRowCount() == 0) {
        JOptionPane.showMessageDialog(null, "There is no tendering request in the table");
      } else {
        JOptionPane.showMessageDialog(null, "Select a tendering request in the table to delete");
      }      
    } else {
      int dialog_button = JOptionPane.YES_NO_OPTION;
      int dialog_result = JOptionPane.showConfirmDialog(null, "Do you want to delete this tender?","Delete confirmation",dialog_button);
      if (dialog_result == 0) {
        String delete_id = products_table.getValueAt(products_table.getSelectedRow(),0)+"";
        model.removeRow(products_table.getSelectedRow());
        Tender tender = new Tender(Integer.parseInt(delete_id));
        ((Manager) manager).deleteTender(tender);
      } 
    }
  }//GEN-LAST:event_delete_buttonActionPerformed

  private void apply_discount_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apply_discount_buttonActionPerformed
    // TODO add your handling code here:
    ManagerTenderApply new_GUI = new ManagerTenderApply();
    new_GUI.setLocationRelativeTo(null);
    new_GUI.setVisible(true);
    this.dispose();
  }//GEN-LAST:event_apply_discount_buttonActionPerformed

  private void formula_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formula_buttonActionPerformed
    // TODO add your handling code here:
    ManagerTenderSetFormula new_GUI = new ManagerTenderSetFormula();
    new_GUI.setLocationRelativeTo(null);
    new_GUI.setVisible(true);
    this.dispose();
  }//GEN-LAST:event_formula_buttonActionPerformed

  private void manage_products_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manage_products_buttonActionPerformed
    // TODO add your handling code here:
    ManagerProducts new_GUI = new ManagerProducts();
    new_GUI.setLocationRelativeTo(null);
    new_GUI.setVisible(true);
    this.dispose();
  }//GEN-LAST:event_manage_products_buttonActionPerformed

  private void logout_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_buttonActionPerformed
    // TODO add your handling code here:
    Login.recordLog(main.staff.getUserName(), "out");
    LoginGUI new_GUI = new LoginGUI();
    new_GUI.setLocationRelativeTo(null);
    new_GUI.setVisible(true);
    this.dispose();
  }//GEN-LAST:event_logout_buttonActionPerformed

  private void report_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_report_buttonActionPerformed
    // TODO add your handling code here:
    ManagerReports new_GUI = new ManagerReports();
    new_GUI.setLocationRelativeTo(null);
    new_GUI.setVisible(true);
    this.dispose();
  }//GEN-LAST:event_report_buttonActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton add_button;
  private javax.swing.JButton apply_discount_button;
  private javax.swing.JButton delete_button;
  private javax.swing.JButton edit_button;
  private javax.swing.JButton formula_button;
  private javax.swing.JTextField id_field;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JButton logout_button;
  private javax.swing.JButton manage_products_button;
  private javax.swing.JTable products_table;
  private javax.swing.JButton report_button;
  private javax.swing.JButton search_button;
  private javax.swing.JButton show_all_button;
  // End of variables declaration//GEN-END:variables

}
